name: SelfECO

on:
  push:
    branches: [ "main","master" ]
  pull_request:
    branches: [ "master","slave" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Python-set-up
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install requests urllib3

    #


    - name: Author Info
      run: |
        echo "Workflow initiated by: ${{ github.actor }}"
        echo "Creator Yotta"


    - name: Build
      run: |
        pyinstaller --onefile --noconsole main.py


    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.${{ github.run_number }}
        name: Release v1.${{ github.run_number }}
        draft: false
        prerelease: false
        files: dist/*.exe 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
